package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alimentacion generated by hbm2java
 */
@Entity
@Table(name = "alimentacion", catalog = "mercadolocal")
public class Alimentacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1985040709591812380L;
	private Integer idalimentacion;
	private Productos productos;
	private Tipoproducto tipoproducto;
	private Integer stock;

	public Alimentacion() {
	}

	public Alimentacion(Productos productos, Tipoproducto tipoproducto) {
		this.productos = productos;
		this.tipoproducto = tipoproducto;
	}

	public Alimentacion(Productos productos, Tipoproducto tipoproducto, Integer stock) {
		this.productos = productos;
		this.tipoproducto = tipoproducto;
		this.stock = stock;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idalimentacion", unique = true, nullable = false)
	public Integer getIdalimentacion() {
		return this.idalimentacion;
	}

	public void setIdalimentacion(Integer idalimentacion) {
		this.idalimentacion = idalimentacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoproducto", nullable = false)
	public Tipoproducto getTipoproducto() {
		return this.tipoproducto;
	}

	public void setTipoproducto(Tipoproducto tipoproducto) {
		this.tipoproducto = tipoproducto;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

}
