package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@Table(name = "municipios", catalog = "mercadolocal")
public class Municipios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6653036410150966072L;
	private Integer idMunicipio;
	private Provincias provincias;
	private String nombre;
	private Integer codMunicipio;
	private Integer dc;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Municipios() {
	}

	public Municipios(Provincias provincias) {
		this.provincias = provincias;
	}

	public Municipios(Provincias provincias, String nombre, Integer codMunicipio, Integer dc, Set<Usuario> usuarios,
			Set<Pedido> pedidos) {
		this.provincias = provincias;
		this.nombre = nombre;
		this.codMunicipio = codMunicipio;
		this.dc = dc;
		this.usuarios = usuarios;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_municipio", unique = true, nullable = false)
	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_provincia", nullable = false)
	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cod_municipio")
	public Integer getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(Integer codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	@Column(name = "DC")
	public Integer getDc() {
		return this.dc;
	}

	public void setDc(Integer dc) {
		this.dc = dc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipios")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipios")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
