package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "mercadolocal")
public class Pedido implements java.io.Serializable {

	private static final long serialVersionUID = -6068551885420076999L;
	private Integer idpedido;
	private Municipios municipios;
	private Provincias provincias;
	private Usuario usuario;
	private Date fechaPedido;
	private Date fechaEntrega;
	private String direccionEntrega;
	private Integer codigopostal;
	private BigDecimal total;
	private BigDecimal descuento;
	private Boolean pagado;
	private String codigopedido;
	private Set<ProductosHasPedido> productosHasPedidos = new HashSet<ProductosHasPedido>(0);

	public Pedido() {
	}

	public Pedido(Usuario usuario) {
		this.usuario = usuario;
	}

	public Pedido(Municipios municipios, Provincias provincias, Usuario usuario, Date fechaPedido, Date fechaEntrega,
			String direccionEntrega, Integer codigopostal, BigDecimal total, BigDecimal descuento, Boolean pagado,
			String codigopedido, Set<ProductosHasPedido> productosHasPedidos) {
		this.municipios = municipios;
		this.provincias = provincias;
		this.usuario = usuario;
		this.fechaPedido = fechaPedido;
		this.fechaEntrega = fechaEntrega;
		this.direccionEntrega = direccionEntrega;
		this.codigopostal = codigopostal;
		this.total = total;
		this.descuento = descuento;
		this.pagado = pagado;
		this.codigopedido = codigopedido;
		this.productosHasPedidos = productosHasPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpedido", unique = true, nullable = false)
	public Integer getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(Integer idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ciudad_entrega")
	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provincia_entrega")
	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pedido", length = 19)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_entrega", length = 19)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "direccion_entrega")
	public String getDireccionEntrega() {
		return this.direccionEntrega;
	}

	public void setDireccionEntrega(String direccionEntrega) {
		this.direccionEntrega = direccionEntrega;
	}

	@Column(name = "codigopostal")
	public Integer getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(Integer codigopostal) {
		this.codigopostal = codigopostal;
	}

	@Column(name = "total", precision = 5)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "descuento", precision = 5)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "pagado")
	public Boolean getPagado() {
		return this.pagado;
	}

	public void setPagado(Boolean pagado) {
		this.pagado = pagado;
	}

	@Column(name = "codigopedido")
	public String getCodigopedido() {
		return this.codigopedido;
	}

	public void setCodigopedido(String codigopedido) {
		this.codigopedido = codigopedido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<ProductosHasPedido> getProductosHasPedidos() {
		return this.productosHasPedidos;
	}

	public void setProductosHasPedidos(Set<ProductosHasPedido> productosHasPedidos) {
		this.productosHasPedidos = productosHasPedidos;
	}
}
