package com.dbarrio.model.dto;
// Generated 10-feb-2017 18:02:20 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductosHasPedido generated by hbm2java
 */
@Entity
@Table(name = "productos_has_pedido", catalog = "mercadolocal")
public class ProductosHasPedido implements java.io.Serializable {

	private static final long serialVersionUID = 3709814690638347461L;
	private ProductosHasPedidoId id;
	private Pedido pedido;
	private Productos productos;
	private Integer cantidad;
	private BigDecimal precio;

	public ProductosHasPedido() {
	}

	public ProductosHasPedido(ProductosHasPedidoId id, Pedido pedido, Productos productos) {
		this.id = id;
		this.pedido = pedido;
		this.productos = productos;
	}

	public ProductosHasPedido(ProductosHasPedidoId id, Pedido pedido, Productos productos, Integer cantidad,
			BigDecimal precio) {
		this.id = id;
		this.pedido = pedido;
		this.productos = productos;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idproductos", column = @Column(name = "idproductos", nullable = false)),
			@AttributeOverride(name = "idpedido", column = @Column(name = "idpedido", nullable = false)) })
	public ProductosHasPedidoId getId() {
		return this.id;
	}

	public void setId(ProductosHasPedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpedido", nullable = false, insertable = false, updatable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproductos", nullable = false, insertable = false, updatable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio", precision = 5)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

}
