package com.dbarrio.model.dto;
// Generated 10-feb-2017 18:02:20 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductosHasPedidoId generated by hbm2java
 */
@Embeddable
public class ProductosHasPedidoId implements java.io.Serializable {

	private static final long serialVersionUID = 8404070749685687766L;
	private int idproductos;
	private int idpedido;

	public ProductosHasPedidoId() {
	}

	public ProductosHasPedidoId(int idproductos, int idpedido) {
		this.idproductos = idproductos;
		this.idpedido = idpedido;
	}

	@Column(name = "idproductos", nullable = false)
	public int getIdproductos() {
		return this.idproductos;
	}

	public void setIdproductos(int idproductos) {
		this.idproductos = idproductos;
	}

	@Column(name = "idpedido", nullable = false)
	public int getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(int idpedido) {
		this.idpedido = idpedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductosHasPedidoId))
			return false;
		ProductosHasPedidoId castOther = (ProductosHasPedidoId) other;

		return (this.getIdproductos() == castOther.getIdproductos()) && (this.getIdpedido() == castOther.getIdpedido());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproductos();
		result = 37 * result + this.getIdpedido();
		return result;
	}

}
