package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "mercadolocal")
public class Productos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1389173930109371581L;
	private Integer idproductos;
	private Subtipo subtipo;
	private Tipo tipo;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private String imagen;
	private BigDecimal precio;
	private Set<Alimentacion> alimentacions = new HashSet<Alimentacion>(0);
	private Set<Ropa> ropas = new HashSet<Ropa>(0);
	private Set<ProductosHasPedido> productosHasPedidos = new HashSet<ProductosHasPedido>(0);

	public Productos() {
	}

	public Productos(Subtipo subtipo, Tipo tipo, Usuario usuario) {
		this.subtipo = subtipo;
		this.tipo = tipo;
		this.usuario = usuario;
	}

	public Productos(Subtipo subtipo, Tipo tipo, Usuario usuario, String nombre, String descripcion, String imagen,
			BigDecimal precio, Set<Alimentacion> alimentacions, Set<Ropa> ropas, Set<ProductosHasPedido> productosHasPedidos) {
		this.subtipo = subtipo;
		this.tipo = tipo;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.precio = precio;
		this.alimentacions = alimentacions;
		this.ropas = ropas;
		this.productosHasPedidos = productosHasPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproductos", unique = true, nullable = false)
	public Integer getIdproductos() {
		return this.idproductos;
	}

	public void setIdproductos(Integer idproductos) {
		this.idproductos = idproductos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsubtipo", nullable = false)
	public Subtipo getSubtipo() {
		return this.subtipo;
	}

	public void setSubtipo(Subtipo subtipo) {
		this.subtipo = subtipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipo", nullable = false)
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen")
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "precio", precision = 5)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Alimentacion> getAlimentacions() {
		return this.alimentacions;
	}

	public void setAlimentacions(Set<Alimentacion> alimentacions) {
		this.alimentacions = alimentacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Ropa> getRopas() {
		return this.ropas;
	}

	public void setRopas(Set<Ropa> ropas) {
		this.ropas = ropas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<ProductosHasPedido> getProductosHasPedidos() {
		return this.productosHasPedidos;
	}

	public void setProductosHasPedidos(Set<ProductosHasPedido> productosHasPedidos) {
		this.productosHasPedidos = productosHasPedidos;
	}
}
