package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Provincias generated by hbm2java
 */
@Entity
@Table(name = "provincias", catalog = "mercadolocal")
public class Provincias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5810289285179728722L;
	private Integer idProvincia;
	private String provincia;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Municipios> municipioses = new HashSet<Municipios>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Provincias() {
	}

	public Provincias(String provincia, Set<Usuario> usuarios, Set<Municipios> municipioses, Set<Pedido> pedidos) {
		this.provincia = provincia;
		this.usuarios = usuarios;
		this.municipioses = municipioses;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_provincia", unique = true, nullable = false)
	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

	@Column(name = "provincia", length = 45)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincias")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincias")
	@OrderBy("nombre asc")
	public Set<Municipios> getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set<Municipios> municipioses) {
		this.municipioses = municipioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincias")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
