package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ropa generated by hbm2java
 */
@Entity
@Table(name = "ropa", catalog = "mercadolocal")
public class Ropa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8164242166509367671L;
	private Integer idropa;
	private Marcas marcas;
	private Productos productos;
	private Tallas tallas;
	private Tipoproducto tipoproducto;
	private Integer stock;

	public Ropa() {
	}

	public Ropa(Marcas marcas, Productos productos, Tallas tallas, Tipoproducto tipoproducto) {
		this.marcas = marcas;
		this.productos = productos;
		this.tallas = tallas;
		this.tipoproducto = tipoproducto;
	}

	public Ropa(Marcas marcas, Productos productos, Tallas tallas, Tipoproducto tipoproducto, Integer stock) {
		this.marcas = marcas;
		this.productos = productos;
		this.tallas = tallas;
		this.tipoproducto = tipoproducto;
		this.stock = stock;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idropa", unique = true, nullable = false)
	public Integer getIdropa() {
		return this.idropa;
	}

	public void setIdropa(Integer idropa) {
		this.idropa = idropa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmarca", nullable = false)
	public Marcas getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Marcas marcas) {
		this.marcas = marcas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtalla", nullable = false)
	public Tallas getTallas() {
		return this.tallas;
	}

	public void setTallas(Tallas tallas) {
		this.tallas = tallas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoproducto", nullable = false)
	public Tipoproducto getTipoproducto() {
		return this.tipoproducto;
	}

	public void setTipoproducto(Tipoproducto tipoproducto) {
		this.tipoproducto = tipoproducto;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

}
