package com.dbarrio.model.dto;
// Generated 17-ene-2017 20:27:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoproducto generated by hbm2java
 */
@Entity
@Table(name = "tipoproducto", catalog = "mercadolocal")
public class Tipoproducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9029637103537354460L;
	private Integer idtipoproducto;
	private String nombre;
	private Set<Ropa> ropas = new HashSet<Ropa>(0);
	private Set<Alimentacion> alimentacions = new HashSet<Alimentacion>(0);
	private Set<Subtipo> subtipos = new HashSet<Subtipo>(0);
	private Set<Tallas> tallases = new HashSet<Tallas>(0);

	public Tipoproducto() {
	}

	public Tipoproducto(String nombre, Set<Ropa> ropas, Set<Alimentacion> alimentacions, Set<Subtipo> subtipos, Set<Tallas> tallases) {
		this.nombre = nombre;
		this.ropas = ropas;
		this.alimentacions = alimentacions;
		this.subtipos = subtipos;
		this.tallases = tallases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipoproducto", unique = true, nullable = false)
	public Integer getIdtipoproducto() {
		return this.idtipoproducto;
	}

	public void setIdtipoproducto(Integer idtipoproducto) {
		this.idtipoproducto = idtipoproducto;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoproducto")
	public Set<Ropa> getRopas() {
		return this.ropas;
	}

	public void setRopas(Set<Ropa> ropas) {
		this.ropas = ropas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoproducto")
	public Set<Alimentacion> getAlimentacions() {
		return this.alimentacions;
	}

	public void setAlimentacions(Set<Alimentacion> alimentacions) {
		this.alimentacions = alimentacions;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tipoproductos")
	public Set<Subtipo> getSubtipos() {
		return this.subtipos;
	}

	public void setSubtipos(Set<Subtipo> subtipos) {
		this.subtipos = subtipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoproducto")
	public Set<Tallas> getTallases() {
		return this.tallases;
	}

	public void setTallases(Set<Tallas> tallases) {
		this.tallases = tallases;
	}

}
